name: Push-to-EC2 instance

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node jobs
        uses: actions/setup-node@v1
        with:
          node-version: "18.17.0"

      - name: Install npm dependencies
        run: npm install --legacy-peer-deps

      - name: Run build task
        run: npm run build

      - name: Copy build to server
        uses: GarryOne/ssh-deploy@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: /home/ubuntu/next

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          script_stop: true
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd next
            npm run dev
            touch .env
